/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ss.app;

import com.ss.list.LinkedList;

import static com.ss.utilities.StringUtils.join;
import static com.ss.utilities.StringUtils.split;
import static com.ss.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import java.util.HashMap;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        var list = new HashMap<String, Integer>();
        System.out.println(WordUtils.capitalize(result));
    }
}
